version: '3.8'

services:
  proxy_server:
    restart: always
    build: ./proxy
    container_name: proxy_server
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data  # Shared folder for SQLite DB

  sqlite_admin:
    restart: always
    build: ./sqlite-web
    container_name: sqlite_admin
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data:ro
